/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "replitcom-merino-desert-storm-merino": "#faf6f1, #f6f5f4, #faf6f1",
        "replitcom-merino": "#faf6f1",
        "replitcom-desert-storm": "#f6f5f4",
        "replitcom-tuna": "#37383c",
        "replitcom-vermilion": "#ff3c00",
        "replitcom-abbey": "#4b4d53",
        "replitcom-international-orange-75": "rgba(253, 84, 2, 0.08)",
        "replitcom-desert-storm1": "#f3f3f1",
        "replitcom-mona-lisa": "#ffb199",
        "replitcom-abbey1": "#55585e",
        "replitcom-cararra": "#f1f0ee",
        "replitcom-timberwolf": "#dbd9d3",
        "replitcom-shuttle-gray": "#696c74",
        "replitcom-desert-storm2": "#f7f7f6",
        "replitcom-cararra1": "#efeeec",
        "replitcom-shark": "#212225",
        "replitcom-white-02": "rgba(255, 255, 255, 0)",
        "replitcom-dusty-gray": "#949494",
        "replitcom-mine-shaft": "#322f2f",
        "replitcom-mine-shaft1": "#312e2e",
        "replitcom-white": "#fff",
        "replitcom-westar": "#dcd5d0",
        "replitcom-black": "#000",
        "replitcom-coral": "#ff764c",
        "replitcom-cod-gray": "#191818",
        "replitcom-westar1": "#dbd4cf",
        "replitcom-coral1": "#ff764d",
        "replitcom-fantasy": "#faf5f0",
        "replitcom-cloud": "#cbc7c3",
        "replitcom-cod-gray1": "#1a1919",
        "replitcom-woodsmoke": "#18191b",
        "replitcom-gray": "#888",
        "replitcom-cararra2": "#edece8",
        "replitcom-shark1": "#2c2e31",
        "replitcom-desert-storm3": "#fcfcfb",
        "replitcom-tuna1": "#36373b",
        "replitcom-mine-shaft2": "#333",
        "replitcom-sisal": "#ddd5cb",
        "replitcom-cod-gray2": "#1a1a1a",
        "replitcom-pearl-bush": "#e8e0d6",
        "replitcom-shuttle-gray1": "#61646b",
        "replitcom-ash": "#c7c4ba",
        "replitcom-white-10": "rgba(255, 255, 255, 0.1)",
        "replitcom-tapa": "#767270",
        "replitcom-natural-gray": "#938f8c",
        "replitcom-tapa1": "#76716f",
      },
    },
    screens: {},
  },
  corePlugins: {
    preflight: false,
  },
};
