"use client";

import { motion } from "framer-motion";
import Header from "@/components/header";
import Footer from "@/components/footer";

type Block = {
  subheading?: string;
  body?: string;
  list?: string[];
};

type Section = {
  id: string;
  number: string;
  heading: string;
  summary?: string;
  blocks: Block[];
};

const sections: Section[] = [
  {
    id: "registration",
    number: "1",
    heading: "Registration and Eligibility",
    summary:
      "You must provide accurate information when creating an account and be at least 13 years old (or the age of legal consent in your jurisdiction).",
    blocks: [
      {
        subheading: "a. Registration.",
        body: "To access the Services, you must register for an account by providing accurate, complete, and current contact details. You agree to maintain and promptly update your account information. Accounts created by automated methods or bots are strictly prohibited.",
      },
      {
        subheading: "b. Minimum Age.",
        body: "The Service is not intended for users under the age of 13. If you are between 13 and the age of legal majority in your jurisdiction, you may only use the Service under the supervision of a parent or legal guardian who agrees to be bound by these Terms.",
      },
      {
        subheading: undefined,
        body: "You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify Rivinity immediately upon discovering any unauthorized access or security breach.",
      },
    ],
  },
  {
    id: "acceptable-use",
    number: "2",
    heading: "Acceptable Use and Restrictions",
    summary:
      "The Service must be used lawfully and strictly in compliance with our acceptable use standards and API safety guardrails.",
    blocks: [
      {
        subheading: "a. Prohibited Conduct.",
        list: [
          "Interfering with, disrupting, or overburdening the Service or its underlying infrastructure",
          "Attempting to circumvent access controls, rate limits, or platform security mechanisms",
          "Reverse engineering, decompiling, or extracting underlying algorithms, model weights, or source code",
          "Uploading viruses, malware, trojans, or malicious code designed to disrupt performance",
          "Automated scraping or bulk extraction of data without prior written authorization from Rivinity",
          "Impersonating any individual, entity, or Rivinity official",
          "Violating third-party privacy, copyright, trademark, or intellectual property rights",
        ],
      },
      {
        subheading: "b. Prohibited Content.",
        list: [
          "Defamatory, abusive, harassing, hate-speech, or illegal content",
          "Content that infringes upon the intellectual property or privacy rights of third parties",
          "Material depicting or facilitating sexual exploitation, violence, or unlawful harm",
          "Prompts designed to bypass model guardrails or generate harmful and malicious exploits",
        ],
      },
      {
        subheading: "c. Privacy Obligations.",
        body: "When using Rivinity to process personal data of third parties, you warrant that you have established a lawful basis and obtained all necessary consents under applicable data protection laws (such as GDPR and CCPA).",
      },
      {
        subheading: "d. Quotas and Limits.",
        body: "Usage is subject to system rate limits, token quotas, and concurrency restrictions associated with your subscription tier. Rivinity reserves the right to adjust limits or throttle traffic to ensure system stability.",
      },
    ],
  },
  {
    id: "content",
    number: "3",
    heading: "Content and Intellectual Property",
    summary:
      "You retain ownership of input data and generated outputs, subject to a limited license allowing Rivinity to deliver and support the Service.",
    blocks: [
      {
        subheading: "a. Your Content and Ownership.",
        body: "You retain all rights, title, and interest in and to the content, prompts, and data you submit ('Inputs') as well as the resulting outputs generated by the AI ('Outputs'). You grant Rivinity a worldwide, non-exclusive license to host, process, reproduce, and display Inputs and Outputs solely to provide, maintain, and improve the Service.",
      },
      {
        subheading: "b. Third-Party Content and Integrations.",
        body: "The Service may integrate with third-party language models, APIs, and services. Rivinity does not control and accepts no liability for third-party platforms or the availability of external API providers.",
      },
      {
        subheading: "c. Rivinity Ownership.",
        body: "Except for user Inputs and Outputs, all rights, title, and interest in and to the Service—including software, user interfaces, branding, logos, proprietary models, and documentation—remain the exclusive property of Rivinity.",
      },
      {
        subheading: "d. Copyright Violations (DMCA).",
        body: "If you believe content hosted on Rivinity infringes your copyright, please submit a written notice of claimed infringement to legal@rivinity.com containing details required under the Digital Millennium Copyright Act.",
      },
    ],
  },
  {
    id: "purchases",
    number: "4",
    heading: "Subscriptions, Pricing, and Refunds",
    summary:
      "Paid plans auto-renew on a recurring basis until canceled, and usage fees are billed as specified in your subscription plan.",
    blocks: [
      {
        subheading: "a. Subscription Terms.",
        body: "Paid subscriptions automatically renew at the end of each billing cycle (monthly or annually) unless canceled prior to the renewal date via your account settings.",
      },
      {
        subheading: "b. Pricing and Usage Fees.",
        body: "Pricing details, API consumption rates, and credit tiers are detailed on our Pricing page. We reserve the right to modify pricing with 30 days' advance notice sent to your registered email.",
      },
      {
        subheading: "c. Refunds.",
        body: "Except as explicitly required by applicable law or stated in writing, all fees paid for subscriptions, token packages, and API usage are non-refundable.",
      },
    ],
  },
  {
    id: "changes-termination",
    number: "5",
    heading: "Notices, Updates, and Termination",
    summary:
      "We may update these Terms or suspend service access for violations, with appropriate notice provided to affected users.",
    blocks: [
      {
        subheading: "a. Modification of Terms.",
        body: "We may update these Terms periodically. Significant changes will be communicated via email or through prominent notice within the app at least 14 days before taking effect.",
      },
      {
        subheading: "b. Service Announcements.",
        body: "By creating an account, you consent to receive administrative, security, operational, and legal notices electronically through the Service or your account email.",
      },
      {
        subheading: "c. Account Termination.",
        body: "You may terminate your account at any time. Rivinity reserves the right to suspend or terminate accounts that breach these Terms, commit fraudulent activity, or create liability for the platform.",
      },
      {
        subheading: "d. Survival.",
        body: "Provisions that by their nature should reasonably survive termination will survive, including intellectual property rights, indemnification, warranty disclaimers, and limitations of liability.",
      },
      {
        subheading: "e. Deprecation of Features.",
        body: "Rivinity may modify, update, or deprecate features or API endpoints. We aim to provide reasonable advance notice prior to discontinuing core features.",
      },
    ],
  },
  {
    id: "disputes",
    number: "6",
    heading: "Limitations and Disclaimers",
    summary:
      "The Service and AI outputs are provided on an 'as-is' basis without warranties of completeness or accuracy.",
    blocks: [
      {
        subheading: "a. AI Output and Content Accuracy.",
        body: "Artificial intelligence outputs are probabilistically generated and may contain inaccuracies, errors, or hallucinations. You are responsible for independently validating and reviewing any Output prior to reliance.",
      },
      {
        subheading: "b. Use at Your Own Risk.",
        body: "Your use of the Service is at your sole risk. The platform is provided without guarantees regarding uninterrupted uptime, error-free operations, or absolute security.",
      },
      {
        subheading: "c. Disclaimer of Warranties.",
        body: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, RIVINITY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.",
      },
      {
        subheading: "d. Limitation of Liability.",
        body: "TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, RIVINITY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOSS OF PROFITS OR DATA. OUR TOTAL LIABILITY SHALL NOT EXCEED THE GREATER OF $100 OR THE AMOUNTS PAID BY YOU TO RIVINITY IN THE 12 MONTHS PRECEDING THE CLAIM.",
      },
      {
        subheading: "e. Indemnification.",
        body: "You agree to defend, indemnify, and hold harmless Rivinity, its officers, directors, and employees against any third-party claims or liabilities arising from your violation of these Terms or misuse of the Service.",
      },
    ],
  },
  {
    id: "resolving-disputes",
    number: "7",
    heading: "Binding Arbitration and Dispute Resolution",
    summary:
      "Disputes will be resolved through individual binding arbitration rather than court proceedings, subject to an opt-out window.",
    blocks: [
      {
        subheading: undefined,
        body: "You and Rivinity agree that any dispute or claim arising out of or relating to these Terms or the Service shall be resolved through final and binding individual arbitration, rather than in court.",
      },
      {
        subheading: "What is arbitration?",
        body: "Arbitration is an informal dispute-resolution process using a neutral arbitrator instead of a judge or jury, allowing for streamlined discovery and faster legal resolution.",
      },
      {
        subheading: "Can claims be part of a class action?",
        body: "No. You and Rivinity agree that all proceedings will be conducted on an individual basis only and not as a class, consolidated, or representative action.",
      },
      {
        subheading: "What is the process to start arbitration?",
        body: "Before initiating formal arbitration, either party must send a written Notice of Dispute describing the claim and desired relief, allowing 30 days to attempt informal negotiation.",
      },
      {
        subheading: "How can I opt out of arbitration?",
        body: "You may opt out of this arbitration agreement within 30 days of creating your account by sending a signed written notice to legal@rivinity.com with the subject line 'Arbitration Opt-Out'.",
      },
    ],
  },
  {
    id: "general-terms",
    number: "8",
    heading: "General Provisions",
    summary:
      "Standard legal provisions regarding governing law, feedback rights, export compliance, and contact details.",
    blocks: [
      {
        subheading: "a. Feedback and Suggestions.",
        body: "If you provide suggestions or feedback regarding Rivinity, we may use and incorporate them into our products without royalty, compensation, or restriction.",
      },
      {
        subheading: "b. Export Control and Sanctions.",
        body: "You represent that you are not located in an embargoed country or listed on any restricted party list maintained by applicable government authorities.",
      },
      {
        subheading: "c. Jurisdiction.",
        body: "These Terms are governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict-of-law principles.",
      },
      {
        subheading: "d. Entire Agreement.",
        body: "These Terms constitute the entire agreement between you and Rivinity regarding the Service and supersede all prior agreements or understandings.",
      },
      {
        subheading: "e. Assignment.",
        body: "You may not assign these Terms without prior written consent. Rivinity may freely assign or transfer its rights under these Terms.",
      },
      {
        subheading: "f. Third-Party APIs.",
        body: "Your use of AI features powered by third-party model providers is subject to their respective policies and guidelines.",
      },
      {
        subheading: "g. Contact Information.",
        body: "If you have any questions regarding these Terms, please contact us at support@rivinity.com.",
      },
    ],
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white text-[#0f172a] font-sans antialiased flex flex-col justify-between">
      <Header />

      <motion.main
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="w-full pt-28 sm:pt-32 md:pt-36 pb-24"
      >
        <div className="mx-auto px-6 sm:px-10 max-w-4xl">
          {/* Header Container */}
          <div className="border-b border-slate-200 pb-8 mb-10">
            <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight text-[#0f172a]">
              Terms and Conditions
            </h1>
            <p className="mt-2.5 text-sm font-medium text-[#64748b]">
              Last updated: August 20, 2026
            </p>

            {/* Introductory Callout Notice */}
            <div className="mt-6 rounded-2xl border border-slate-200 bg-[#F7F7F8] p-5 text-sm leading-relaxed text-[#64748b]">
              This agreement governs your access to and use of the Services and is
              between you and Rivinity, Inc. ("Rivinity", "we," "us," or "our") and is
              binding on you individually and, if applicable, on behalf of any entity
              or business you represent. Please read these Terms carefully. If you do
              not agree, you must not use the Services.
              <br />
              <br />
              <strong className="text-[#0f172a]">NOTICE REGARDING ARBITRATION:</strong> PLEASE NOTE THAT SECTION 7
              CONTAINS AN ARBITRATION AGREEMENT THAT REQUIRES ALL DISPUTES TO BE
              RESOLVED ON AN INDIVIDUAL BASIS THROUGH BINDING ARBITRATION RATHER THAN IN
              COURT OR JURY TRIALS, UNLESS YOU OPT OUT WITHIN 30 DAYS.
            </div>
          </div>

          {/* Main Body Content */}
          <div className="space-y-10">
            {sections.map((section) => (
              <div key={section.id} id={section.id} className="scroll-mt-24">
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#1A1A1A] tracking-tight">
                  {section.number}. {section.heading}
                </h2>
                {section.summary && (
                  <p className="mt-2 text-sm sm:text-base font-semibold text-[#6B7280]">
                    {section.summary}
                  </p>
                )}

                <div className="mt-4 space-y-4">
                  {section.blocks.map((block, idx) => (
                    <div key={idx} className="text-sm sm:text-base leading-relaxed text-[#4B5563]">
                      {block.subheading ? (
                        <p>
                          <span className="font-bold text-[#1A1A1A] mr-2">
                            {block.subheading}
                          </span>
                          {block.body}
                        </p>
                      ) : (
                        block.body && <p>{block.body}</p>
                      )}

                      {"list" in block && block.list && (
                        <ul className="mt-2 list-disc pl-6 space-y-1.5">
                          {block.list.map((item: string) => (
                            <li key={item}>{item}</li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}

            <div className="pt-8 border-t border-[#E5E7EB] text-sm text-[#6B7280]">
              Disclaimer: While this document provides production-ready terms for a platform launch, consult with your company's legal counsel to ensure compliance with specific jurisdictional laws.
            </div>
          </div>

        </div>
      </motion.main>

      <Footer />
    </div>
  );
}